import type { Metadata } from "next";
import { PreLoginNav } from "@/components/PreLoginNav";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: { absolute: "Changelog — PledgeOFF" },
  description: "What's new in PledgeOFF — every release, every fix, every improvement.",
  alternates: { canonical: "https://pledgeoff.com/changelog" },
  robots: { index: true, follow: true },
};

const RELEASES = [
  {
    version: "1.1",
    date: "May 2026",
    tag: "UI",
    items: [
      "Two-column layout on idea page — verdict sticky left, signals scrollable right",
      "Compact signal cards: title truncated, sentiment dot, View ↗ button",
      "Light mode repaired — accent color (#4D6C00 olive), canvas/surface separation, visible borders",
      "ThemeToggle: 3 buttons replaced with single dropdown",
    ],
  },
  {
    version: "1.0",
    date: "May 2026",
    tag: "SIGNALS",
    items: [
      "LLM-generated search queries replace keyword extractor — signals now match full idea text",
      "GitHub: removed sort=reactions (now uses best-match ranking) + in:title qualifier",
      "Reddit: removed type filter that silently returned 0 results",
      "Parallel fetch: 2 queries × 2 sources, deduplicated by URL before save",
      "Prod DB synced — 6 missing migrations applied via supabase db push",
    ],
  },
  {
    version: "0.9",
    date: "May 2026",
    tag: "UI",
    items: [
      "Full nav redesign — all actions consistently visible",
      "Footer with social icons (X, TikTok, Instagram)",
      "Sticky header across all pages",
      "Consistent typographic hierarchy across the entire site",
    ],
  },
  {
    version: "0.8",
    date: "May 2026",
    tag: "DESIGN",
    items: [
      "Dashboard redesign with sparklines and visual pipeline",
      "Animated loading screen with 3 progress panels",
      "Evidence wall with animated score count-up and glow effect",
      "Score dimensions: Market Demand, Competition, Feasibility, Timing",
    ],
  },
  {
    version: "0.7",
    date: "May 2026",
    tag: "CONTENT",
    items: [
      "Blog index and article pages with ToC and reading progress bar",
      "Full Privacy Policy (GDPR, sub-processors, rights Art. 15–21)",
      "Terms of Service (billing, trial, refund policy, governing law EU)",
      "Cookie banner with consent management",
    ],
  },
  {
    version: "0.6",
    date: "May 2026",
    tag: "INTELLIGENCE",
    items: [
      "AI verdict generated by Groq with Zod-validated schema",
      "Versioned prompt (decision-prompt.v1) with 4 weighted dimensions",
      "Score calculated from weighted average (Market Demand ×0.4, etc.)",
      "Full idempotency — each event processed exactly once",
    ],
  },
  {
    version: "0.5",
    date: "May 2026",
    tag: "SIGNALS",
    items: [
      "Reddit adapter — live scraping via Reddit public JSON API",
      "GitHub adapter — issues tagged with sentiment from reactions",
      "Postgres event bus with outbox pattern and cron retry",
      "Graceful degradation when a source is down",
    ],
  },
  {
    version: "0.1",
    date: "Apr 2026",
    tag: "LAUNCH",
    items: [
      "First deploy on pledgeoff.com",
      "Email auth and Google OAuth via Supabase",
      "POST /api/v1/ideas → real-time verdict",
      "RLS enabled on all tables from day one",
    ],
  },
];

const TAG_COLORS: Record<string, string> = {
  UI:          "var(--accent)",
  DESIGN:      "var(--validated)",
  CONTENT:     "var(--caution)",
  INTELLIGENCE:"var(--accent)",
  SIGNALS:     "var(--validated)",
  FIX:         "var(--caution)",
  LAUNCH:      "var(--accent)",
};

export default function ChangelogPage() {
  return (
    <div style={{ background: "var(--canvas)", color: "var(--t1)" }}>
      <PreLoginNav />

      {/* Heading — sticky below PreLoginNav */}
      <section
        className="border-b sticky top-12 z-40"
        style={{ borderColor: "var(--border)", background: "var(--canvas)" }}
      >
        <div className="max-w-275 mx-auto px-8 py-12">
          <div className="mono text-[10px] uppercase tracking-wider mb-3" style={{ color: "var(--t3)" }}>
            CHANGELOG · RELEASES
          </div>
          <h1
            className="display font-semibold"
            style={{ fontSize: "32px", letterSpacing: "-0.04em", color: "var(--t1)" }}
          >
            What&apos;s shipped.
          </h1>
          <p className="mt-3 text-[13px] max-w-120" style={{ color: "var(--t2)" }}>
            Every meaningful change — features, fixes, and improvements — in reverse chronological order.
          </p>
        </div>
      </section>

      {/* Releases */}
      <div className="max-w-275 mx-auto px-8 py-12 space-y-0">
        {RELEASES.map((r, i) => (
          <div
            key={r.version}
            className="grid grid-cols-12 gap-8 py-8"
            style={{ borderBottom: i < RELEASES.length - 1 ? "1px solid var(--border)" : "none" }}
          >
            {/* Left — version + date */}
            <div className="col-span-3">
              <div className="mono text-[11px] font-semibold" style={{ color: "var(--t1)" }}>
                v{r.version}
              </div>
              <div className="mono text-[10px] mt-1" style={{ color: "var(--t3)" }}>
                {r.date}
              </div>
              <span
                className="inline-block mt-3 mono text-[9px] uppercase tracking-widest px-2 py-0.5 rounded"
                style={{
                  color: TAG_COLORS[r.tag] ?? "var(--t3)",
                  background: `color-mix(in srgb, ${TAG_COLORS[r.tag] ?? "var(--t3)"} 12%, transparent)`,
                  border: `1px solid color-mix(in srgb, ${TAG_COLORS[r.tag] ?? "var(--t3)"} 30%, transparent)`,
                }}
              >
                {r.tag}
              </span>
            </div>

            {/* Right — items */}
            <ul className="col-span-9 space-y-2">
              {r.items.map((item) => (
                <li key={item} className="flex items-start gap-3 text-[13px]" style={{ color: "var(--t2)" }}>
                  <span className="mt-1.25 w-1 h-1 rounded-full shrink-0" style={{ background: "var(--accent)" }} />
                  {item}
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
      <Footer />
    </div>
  );
}
